export const hallOptions: string[] = [
    'Salimullah Muslim Hall',
    'Fazlul Huq Muslim Hall',
    'Zahurul Haque Hall',
    'Surja Sen Hall',
    'Amar Ekushey Hall',
    'A.F. Rahman Hall',
    'Muktijoddha Ziaur Rahman Hall',
    'Bangabandhu Sheikh Mujibur Rahman Hall',
    'Haji Muhammad Mohsin Hall',
    'Sergeant Zahurul Huq Hall',
    'Dr. Muhammad Shahidullah Hall',
    'Jagannath Hall',
    'Sir P J Hartog International Hall',
    'Ruqayyah Hall',
    'Shamsun Nahar Hall',
    'Bangladesh-Kuwait Maitree Hall',
    'Begum Fazilatun Nesa Mujib Hall',
    'Kabi Sufia Kamal Hall',
  ];